<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <ApplicationIcon>WH3CharacterManager.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="WH3CharacterManager.ico" />
      <EmbeddedResource Include="Assets\names_db.json" />
      <Compile Remove="Tests\**" />
      <None Remove="Tests\**" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="ZstdSharp.Port" Version="0.8.8" />
    </ItemGroup>

</Project>
